---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: vault
spec:
  ca:
    secretName: kube-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-certificate
  namespace: vault
spec:
  secretName: vault-tls
  duration: 9125h # 1y
  renewBefore: 360h # 15d
  subject:
    organizations:
    - pavel k8s
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  dnsNames:
  - vault.local
  ipAddresses:
  - 192.168.1.55
  - 192.168.1.56
  - 192.168.1.57
  issuerRef:
    name: vault-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
