apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vault
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /nfs/vault/data/pv
    server: 192.168.1.55
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#      - matchExpressions:
#        - key: kubernetes.io/hostname
#          operator: In
#          values:
          # - node2.kryukov.local
#          - node3.kryukov.local
  persistentVolumeReclaimPolicy: Retain
